
/**************************************************************
 *	
 *	loop, 8 bit, 44100Hz,
 *	1 channel, 220500 bytes/channel
 *	Total Size: 1 * 220500 + 4 (header) = 220544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Documents\My Dropbox\_school\2261\loop.wav
 *	Time-stamp: Tue Apr 17 23:09:22 2012
 *	
 **************************************************************/

#ifndef __LOOPH__
#define __LOOPH__

#define LOOPFREQ 44100
#define LOOPLEN 220500

extern const unsigned char loop[220500];

#endif /* __LOOPH__ */
