
/**************************************************************
 *	
 *	strike1, 8 bit, 11025Hz,
 *	1 channel, 10185 bytes/channel
 *	Total Size: 1 * 10185 + 4 (header) = 10229 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Documents\My Dropbox\_school\2261\strike1.wav
 *	Time-stamp: Fri Apr 13 01:22:54 2012
 *	
 **************************************************************/

#ifndef __STRIKE1H__
#define __STRIKE1H__

#define STRIKE1FREQ 11025
#define STRIKE1LEN 10185

extern const unsigned char strike1[10185];

#endif /* __STRIKE1H__ */
